services:
  - type: web
    name: zingaroebike
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: database
      mountPath: /data
      sizeGB: 1
